# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        rebl:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
